name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Install dependencies for WebKit # Only for WebKit
        run: sudo apt-get update && sudo apt-get install -y \
          libgtk-4-1 \
          libgraphene-1.0-0 \
          libwoff2dec1 \
          libvpx6 \
          libevent-2.1-7 \
          libopus0 \
          libgst-plugins-base1.0-0 \
          libgst-plugins-good1.0-0 \
          libgstreamer1.0-0 \
          libgstvideo-1.0-0 \
          libflite1 \
          libavif0 \
          libharfbuzz-icu0 \
          libsecret-1-0 \
          libhyphen0 \
          libmanette-0.2-0 \
          libgles2 \
          libx264-155

      - name: Run tests
        env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: npm test
        continue-on-error: true

      - name: Zip Playwright report
        run: zip -r playwright-report.zip playwright-report/

      - name: Send email notification
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
        run: node sendmail/sendMail.js
